---
- hosts: all
  gather_facts: no
  ignore_unreachable: yes
  vars:
    - ansible_python_interpreter: auto_silent
    - ansible_python_interpreter: /usr/bin/python
  tasks:
    - name: Checking if {{ user }} user exists
      shell: id -u {{ user }}
      register: user_exists
      ignore_errors: true
    - name: Checking if {{ group }} group exists
      shell: grep -q {{ group }} /etc/group
      register: group_exists
      ignore_errors: true
    - name: creating "{{ group }}"
      group:
        name: "{{ group }}"
        state: present
      when: user_exists.rc == 0 and group_exists.rc != 0
    - name: Adding user "{{ user }}" to "{{ group }}"
      user:
        name: "{{ user }}"
        groups: "{{ group }}"
        append: yes
      when: user_exists.rc == 0
