---
- hosts: all
  gather_facts: no
  ignore_unreachable: yes
  vars:
    - ansible_python_interpreter: auto_silent
    - ansible_python_interpreter: /usr/bin/python
  tasks:
    - name: Message
      debug:
        mgs: User Creation will take time, come back to check the status. If the Job fails inform Kennedy.
      when: inventory_hostname == admin      
    - name: Checking if {{ user }} user exists
      shell: id -u {{ user }}
      register: user_exists
      ignore_errors: true
    - name: Creating user {{ comment }} with ID {{ user }} on all hosts
      user:
        name: "{{ user }}"
        comment: "{{ comment }}"
        password: "{{ password | password_hash('sha512') }}"
        state: present
      when: user_exists.rc != 0
    - name: Setting password on AIX
      shell: "echo \"{{ user }}:{{ password }}\"|chpasswd"
      when: user_exists.rc != 0 and (inventory_hostname in groups['aix'])
