---
- hosts: all
  gather_facts: no
  ignore_unreachable: yes
  vars:
    - ansible_python_interpreter: auto_silent
    - ansible_python_interpreter: /usr/bin/python
  tasks:
    - name: Checking sidadm user
      shell: cat /etc/passwd|grep adm|grep SAP|grep -v sapadm|grep -v daaadm|awk -F ":" '{print $1}' 
      register: sidadm
      ignore_errors: true
    - name: Reseting SAP sidadm password on Linux servers
      user:
        name: "{{ item }}"
        update_password: always
        password: "{{ password | password_hash('sha512') }}"
        password_lock: false
      with_items: sidadm.stdout_lines[0]
      when: sidadm.rc == 0 and (inventory_hostname in groups['redhat'] or inventory_hostname in groups['suse'])
    - name: Resetting SAP sidadm password on AIX servers
      shell: "echo \"{{ item }}:{{ password }}\"|chpasswd -c"
      with_items: sidadm.stdout_lines[0]
      when: sidadm.rc == 0 and (inventory_hostname in groups['aix'])
    - name: Message
      debug:
        msg: "SAP is not running"
      when: sidadm.rc != 0
