---
- hosts: "{{ target }}"
  gather_facts: no
  ignore_unreachable: yes
  vars:
    - ansible_python_interpreter: auto_silent
    - ansible_python_interpreter: /usr/bin/python
  tasks:
    - name: Checking if {{ user }} user exists
      shell: id -u {{ user }}
      register: user_exists
      ignore_errors: true
    - name: Message
      debug:
        msg: "{{ user }} already exist!, Skipping the next steps"
      when: user_exists.rc == 0
        #   - name: creating "{{ group }}"
        # group:
        # name: "{{ group }}"
        #state: present
        #when: user_exists.rc != 0
    - name: Creating "{{ comment }}" with ID "{{ user }}" in servers "{{ target }}" 
      user:
        name: "{{ user }}"
        groups: "{{ group }}"
        append: yes 
        comment: "{{ comment }}"
        password: "{{ password | password_hash('sha512') }}"
        state: present
      when: user_exists.rc != 0
    - name: Setting password on AIX
      shell: "echo \"{{ user }}:{{ password }}\"|chpasswd"
      when: user_exists.rc != 0 and (inventory_hostname in groups['aix'])
