---
- hosts: "{{ target }}"
  gather_facts: no
  ignore_unreachable: yes
  collections:
  - ibm.power_aix
  tasks:
    - block:
        - fail: msg="Please check the server name. This is not an AIX machine"
          when: "'aix' not in group_names"
        - name: "Mounting MPPS pcdcmksaxap01 NFS"
          command: "mount 10.128.41.15:/mksysb /bkpmksysb"
          ignore_errors: true
          when: inventory_hostname in groups['mppsaix']
          register: nfsmountmpps
        - name: "Mounting CAPT pcdcmksaxap02 NFS"
          command: "mount 10.0.48.22:/mksysb /bkpmksysb"
          register: nfsmountcapt
          ignore_errors: true
          when: inventory_hostname in groups['captaix']
        - debug:
            msg: There is an issue with MPPS NF pcdcmksaxap01 to {{ inventory_hostname }}, Please check
          when:  "inventory_hostname in groups['mppsaix'] and (nfsmountmpps.rc != 0)"
        - debug:
            msg: There is an issue with CAPT NFS mount pcdcmksaxap02 to {{ inventory_hostname }}, Please check
          when:  "inventory_hostname in groups['captaix'] and (nfsmountcapt.rc != 0)"
        - name: "Runing mksysb backup"
          backup:
            action: create
            type: mksysb
            location: /bkpmksysb/{{inventory_hostname}}.mksysb
            exclude_files: yes
            extend_fs: yes
            create_data_file: yes
            force: yes
          register: mksys
          failed_when: "'Completed Successfully' not in mksys.stdout"
      always:
        - pause:
            minutes: 1
          run_once: True
        - name: "Unmounting NFS"
          command: "umount /bkpmksysb"
          ignore_errors: true