---
- name: Resetting User password
  hosts: "{{ target }}"
  gather_facts: no
  ignore_unreachable: yes
  vars:
    - ansible_python_interpreter: /usr/bin/python
  tasks:
    - name: Checking if {{ user }} user exists
      shell: id -u {{ user }}
      register: user_exists
      ignore_errors: true
    - name: Message
      fail:
        msg: "{{ user }} doesnot exist"
      when: user_exists.rc != 0
    - name: Reseting {{ user }} password on Linux
      shell: "echo \"{{ user }}:{{ password }}\"|sudo /usr/sbin/chpasswd"
      when: user_exists.rc == 0 and (inventory_hostname in groups['linux'])
    - name: Reseting {{ user }} password on AIX
      shell: "echo \"{{ user }}:{{ password }}\"|sudo chpasswd -c"
      when: user_exists.rc == 0 and (inventory_hostname in groups['aix'])
    - name: Resetting failed login count on AIX
      shell: "sudo chuser unsuccessful_login_count=0 {{ user }}"
      when: user_exists.rc == 0 and (inventory_hostname in groups['aix'])