---
- hosts: "{{ target }}"
  gather_facts: no
  ignore_unreachable: yes
  collections:
    - community.general
  vars:
    - ansible_python_interpreter: /usr/bin/python
    - myusers: ['root', 'bin', 'mail', 'awxadm', '*adm', 'oracle', 'jenkins']
    - unixteam: ['kumarv25', 'ganjab81', 'x1vasuna', 'meixnj63', 'inampk48', 'x1shukla', 'x1jinusu']
  tasks:
    - name: Message
      fail:
        msg: "{{ user }} is a generic account. DO NOT ATTEMPT TO REMOVE THIS ACCOUNT!"
      when: user in myusers
    - name: Message
      fail:
        msg: "{{ user }} belongs to Unixteam. PLEASE CHECK WITH UNIXTEAM!"
      when: user in unixteam
    - name: check ID
      shell: id -u {{ user }}
      register: user_exists
      ignore_errors: true
    - fail:
        msg: "User {{ user }} doesnot exist!"
      when: user_exists.rc == 1
    - name: copy passwd file 
      shell: >
        cp /etc/passwd /etc/passwd-`date +%d%b%y`
    - name: Getting user home dir
      shell: >
         cat /etc/passwd|grep {{ user }}|awk -F: '{print $6}'
      register: homedir
    - name: archiving {{ user }} home dir
      archive:
        path: "{{ homedir.stdout }}"
        dest: "{{ homedir.stdout }}.tar.gz"
        format: gz
        force_archive: true
    - name: Removing {{ user }} from {{ target }}
      user:
        name: "{{ user }}"
        state: absent
        remove: yes
      when: user not in myusers and (user not in unixteam)
