---
- hosts: "{{ target }}"
  gather_facts: no
  ignore_unreachable: yes
  tasks:
    - lineinfile:
        path: /var/spool/cron/crontabs/root
        regexp: "/mksysb.backup" 
        state: absent
        backup: yes