---
- hosts: "{{ target }}"
  gather_facts: no
  ignore_unreachable: yes
  vars:
    - ansible_python_interpreter: auto_silent
    - ansible_python_interpreter: /usr/bin/python
  tasks:
    - name: Checking if {{ user }} user exists
      shell: id -u {{ user }}
      register: user_exists
      ignore_errors: true
    - name: Checking if {{ group }} group exists
      shell: grep -q {{ group }} /etc/group
      register: group_exists
      ignore_errors: true
    - name: Message
      debug: 
        msg: "User {{ user }} does not exist, skipping the next steps."
      when: user_exists.rc != 0
    - name: Message
      debug:
        msg: "Group {{ group }} does not exist, skipping the next steps."
      when: group_exists.rc != 0   
    - name: Adding user "{{ user }}" to "{{ group }}"
      user:
        name: "{{ user }}"
        groups: "{{ group }}"
        append: yes
      when: user_exists.rc == 0 and group_exists.rc == 0
