---
- name: Lock Users 
  hosts: "{{ target }}" 
  gather_facts: no
  ignore_unreachable: yes
  any_errors_fatal: false
  vars:
    - ansible_python_interpreter: /usr/bin/python
    - myusers: ['awxadm', 'root', 'inampk48']
  tasks:
    - name: Warn about generic accounts
      debug:
        msg: "{{ user }} is a generic account. DO NOT ATTEMPT TO LOCK THIS ACCOUNT!"
      when: user in myusers

    - name: Check if the user exists {{ user }}
      shell: id -u {{ user }}
      register: user_exists
      ignore_errors: true
    
    - name: Locking {{ user }} Linux 
      shell: "passwd -l {{ user }}"
      when: "user_exists.rc == 0 and inventory_hostname in groups['linux'] and user not in myusers"
    
    - name: Locking {{ user }} AIX
      shell: "chuser account_locked=true {{ user }}"
      when: "user_exists.rc == 0 and inventory_hostname in groups['aix'] and user not in myusers"
    
    - name: User does not exist
      debug:
        msg: "{{ user }} doesnot exist"
      when: user_exists.rc != 0
