---
- hosts: "{{ target }}"
  gather_facts: no
  ignore_unreachable: yes
  vars:
    - ansible_python_interpreter: auto_silent
    - ansible_python_interpreter: /usr/bin/python
  tasks:
    - name: Checking if {{ user }} user exists
      shell: id -u {{ user }}
      register: user_exists
      ignore_errors: true
        #    - name: Message
        # debug:
        # msg: "{{ user }} already exist!, Skipping the next steps"
        #when: user_exists.rc == 0
    - name: Modifying user 
      user:
        name: "{{ user }}"
        groups: "{{ group }}"
        append: yes
        comment: "{{ comment }}"
          #        password: "{{ password | password_hash('sha512') }}"
#        state: present
      when: user_exists.rc == 0
#    - name: Setting password on AIX
#      shell: "echo \"{{ user }}:{{ password }}\"|chpasswd"
#      when: user_exists.rc != 0 and (inventory_hostname in groups['aix'])
    - name: Message
      debug:
        msg: "{{ user }} userid does not exist"
      when: user_exists.rc != 0
