---
- name: Resetting my password
  hosts: "{{ target }}" 
  gather_facts: no
  ignore_unreachable: yes
  vars:
    - ansible_python_interpreter: auto_silent
    - ansible_python_interpreter: /usr/bin/python
  tasks:
    - name: Checking if {{ awx_user_name }} user exists
      shell: id -u {{ awx_user_name }}
      register: user_exists
      ignore_errors: true
    - name: Reseting {{ awx_user_name }} password on Linux servers
      shell: "echo \"{{ awx_user_name }}:{{ password }}\"|sudo /usr/sbin/chpasswd"
      when: user_exists.rc == 0 and (inventory_hostname in groups['linux'] or inventory_hostname in groups['sap_linux'] or inventory_hostname in groups['dba_linux'])
    - name: Resetting {{ awx_user_name }} password on AIX servers
      shell: "echo \"{{ awx_user_name }}:{{ password }}\"|sudo chpasswd -c"
      when: user_exists.rc == 0 and (inventory_hostname in groups['aix'])
    - name: Resetting failed login count on AIX
      shell: "sudo chuser unsuccessful_login_count=0 {{ awx_user_name }}"
      when: user_exists.rc == 0 and (inventory_hostname in groups['aix'] or inventory_hostname in groups['sap_aix'] or inventory_hostname in groups['dba_aix'])
    - name: Message
      debug:
        msg: "{{ awx_user_name }} doesnot exist"
      when: user_exists.rc != 0
