---
- name: Setting Non-Expiry for user
  hosts: "{{ target }}" 
  gather_facts: no
  ignore_unreachable: yes
  vars:
    - ansible_python_interpreter: auto_silent
    - ansible_python_interpreter: /usr/bin/python
  tasks:
    - name: Checking if {{ user }} user exists
      shell: id -u {{ user }}
      register: user_exists
      ignore_errors: true
    - name: Setting Non-Expiry for user {{ user }} on Linux servers
      shell: "chage -I -1 -m 0 -M 99999 -E -1 {{ user }}"
      when: user_exists.rc == 0 and (inventory_hostname in groups['linux'] or inventory_hostname in groups['sap_linux'] or inventory_hostname in groups['dba_linux']) 
    - name: Setting Non-Expiry for user {{ user }} on AIX servers
      shell: "chuser maxage=0 {{ user }}"
      when: user_exists.rc == 0 and (inventory_hostname in groups['aix'] or inventory_hostname in groups['sap_aix'] or inventory_hostname in groups['dba_aix'])
    - name: Message
      debug:
        msg: "{{ user }} doesnot exist"
      when: user_exists.rc != 0
