- name: Random Password generator
  hosts: localhost
  gather_facts: False 

  tasks:
   - set_fact:
       my_pass: "{{ lookup('password', '/dev/null length=12 chars=ascii_letters,digits,punctuation') }}"
     no_log: true
   - name: Random Password
     debug:
       msg: "{{ my_pass }}"
