---
- name: Resetting root password
  hosts: "{{ target }}" 
  gather_facts: no
  ignore_unreachable: yes
  vars:
    - ansible_python_interpreter: auto_silent
    - ansible_python_interpreter: /usr/bin/python
  tasks:
    - name: Reseting root password on Linux servers
      user:
        name: root
        update_password: always
        password: "{{ password | password_hash('sha512') }}"
      #   shell: "echo \"{{ awx_user_name }}:{{ password }}\"|sudo /usr/sbin/chpasswd"
      when: inventory_hostname in groups['linux']
    - name: Resetting root password on AIX servers
      shell: "echo \"root:{{ password }}\"|sudo chpasswd -c"
      when: inventory_hostname in groups['aix']
    - name: Resetting failed login count on AIX
      shell: "sudo chuser unsuccessful_login_count=0 root"
      when: inventory_hostname in groups['aix']
