---
- name: Password Reset
  hosts: "{{ target }}" 
  gather_facts: no
  ignore_unreachable: yes
  vars:
    - ansible_python_interpreter: auto_silent
    - ansible_python_interpreter: /usr/bin/python
    - myusers: ['awxadm', 'root', 'inampk48']
  tasks:
    - name: Validating the user {{ user }}
      shell: id -u {{ user }}
      register: user_exists
      ignore_errors: true
    - name:  Message
      debug:
        msg: "{{ user }} is a generic account. DO NOT ATTEMPT TO LOCK THIS ACCOUNT!"
      when: user in myusers
    - name: Unlocking {{ user }} on Linux server
      shell: "passwd -u {{ user }}"
      when: user_exists.rc == 0 and (inventory_hostname in groups['linux'] or inventory_hostname in groups['sap_linux'] or inventory_hostname in groups['dba_linux'])  and (user not in myusers)
    - name: Unlocking {{ user }} on AIX Server
      shell: "chuser account_locked=false unsuccessful_login_count=0 {{ user }}"
      when: user_exists.rc == 0 and (inventory_hostname in groups['aix']  or inventory_hostname in groups['sap_aix'] or inventory_hostname in groups['dba_aix'])  and (user not in myusers)
    - name: Message
      debug:
        msg: "{{ user }} doesnot exist"
      when: user_exists.rc != 0
