---
- hosts: "{{ target }}"
  gather_facts: no
  collections:
    - ibm.power_aix
  tasks:
    - fail: msg="Please check the server name. This is not an AIX machine"
      when: "'aix' not in group_names" 
    - name: "Checking for alternate disk"
      shell: lspv|grep altinst_rootvg|awk '{print $1}'
      register: altdisk
    - fail: msg="No alt clone disk found"
      when: altdisk.stdout  == ""
    - name: Cleaning old copy
      alt_disk:
        action: clean
    - name: Creating new alt_disk
      alt_disk:
        action: copy
        targets: "{{ altdisk.stdout_lines[0] }}"
