---
- hosts: "{{ target }}"
  gather_facts: no
  tasks:
    - fail: msg="Please check the server name. This is not an AIX machine"
      when: "'aix' not in group_names"
    - name: "Mounting NFS"
      command: "mount 134.238.142.243:/mksysb /mnt"
      register: nfsmount
      ignore_errors: true
    - debug:
        msg: There is an issue with NFS mount, Please check
      when:  nfsmount.rc != 0
    - name: "Runing mksysb backup"
      mksysb:
        name: "{{inventory_hostname}}.mksysb"
        storage_path: /mnt
        exclude_files: yes
      when: nfsmount.rc == 0
      register: mksys
      failed_when: '"mksysb: Backup Completed Successfully" not in mksys._msg'
        # ignore_errors: true
    - pause:
        minutes: 2
#    - debug:
#        var: mksys
    - name: "Unmounting NFS"
      mount:
        path: "/mnt"
        state: unmounted
      ignore_errors: true
      when:  nfsmount.rc == 0
        #    - fail: msg="Few servers Mksysb might not be sucessfull"
      #      when: '"mksysb: Backup Completed Successfully" not in mksys._msg'
