---
- hosts: all
  gather_facts: no
  ignore_unreachable: yes
  vars:
    - ansible_python_interpreter: /usr/bin/python 
  tasks:
    - name: pinging the servers
      ping:
      when:  "'exception' not in group_names"
