---
- hosts: "{{ target }}"
  gather_facts: no
  ignore_unreachable: yes
  collections:
  - ibm.power_aix
  tasks:
    - block:
        - fail: msg="Please check the server name. This is not an AIX machine"
          when: "'aix' not in group_names"
        - name: "Mounting MPPS pcdcmksaxap01 NFS"
          command: "mount 10.128.41.15:/mksysb /bkpmksysb"
          ignore_errors: true
          when: inventory_hostname in groups['mppsaix']
          register: nfsmountmpps
          tags: rerun
        - name: "Mounting CAPT pcdcmksaxap02 NFS"
          command: "mount 10.0.48.22:/mksysb /bkpmksysb"
          register: nfsmountcapt
          ignore_errors: true
          when: inventory_hostname in groups['captaix']
          tags: rerun
        - name: MPPS nfs mount message
          debug:
            msg: There is an issue with MPPS NF pcdcmksaxap01 to {{ inventory_hostname }}, Please check
          when:  "inventory_hostname in groups['mppsaix'] and (nfsmountmpps.rc != 0)"
        - name: CAPT nfs mount message
          debug:
            msg: There is an issue with CAPT NFS mount pcdcmksaxap02 to {{ inventory_hostname }}, Please check
          when:  "inventory_hostname in groups['captaix'] and (nfsmountcapt.rc != 0)"
        - name: "Runing mksysb backup"
          backup:
            action: create
            type: mksysb
            location: /bkpmksysb/{{inventory_hostname}}.mksysb
            exclude_files: yes
            extend_fs: yes
            create_data_file: yes
            force: yes
          #when: (nfsmountmpps.rc == 0) or (nfsmountcapt.rc == 0)
          register: mksys
          failed_when: "'Completed Successfully' not in mksys.stdout"
          tags: rerun
      always:
        - pause:
            minutes: 1
          run_once: True
        - name: "Unmounting NFS"
          command: "umount /bkpmksysb"
          #when: (nfsmountmpps.rc == 0) or (nfsmountcapt.rc == 0)
          ignore_errors: true
          tags: rerun
        - local_action: shell date +%d-%b-%y
          register: date
          run_once: True
        - name: Copy output to file
          copy:
            dest: /home/inampk48/mksysb_error_report.out
            content: |-
              {% for host in ansible_play_hosts_all %}
              {% if hostvars[host]['mksys'] is defined and 'Completed Successfully' not in hostvars[host]['mksys']['stdout'] %}
              {{ '###' }}{{ host }}{{ '###' }}
              {{ '--------------------------' }}
              {{ hostvars[host]['mksys']['stdout'] }}
              {{ hostvars[host]['mksys']['stderr'] }}
              {% endif %}
              {% endfor %}
          run_once: True
          delegate_to: pcdcawxlxap01
        - name: Mailling mksysb error report
          mail:
            subject: Mksysb error report - MPPS
            body: "{{ lookup('template','report_v2.j2') }}"
            from: "Unix Mksysb Automation <root@pcdcawxlxap01.driv.com>"
            to:
              - giosunix@driv.com
            cc:
              - kennedy.inampudi@driv.com
            attach:
              - /home/inampk48/mksysb_error_report.out
            subtype: html
            charset: utf8
          run_once: True
          delegate_to: pcdcawxlxap01
          when: inventory_hostname in groups['mppsaix']
        - name: Mailling mksysb error report
          mail:
            subject: Mksysb error report - CAPT
            body: "{{ lookup('template','report_v2.j2') }}"
            from: "Unix Mksysb Automation <root@pcdcawxlxap01.driv.com>"
            to:
              - giosunix@driv.com
            cc:
              - kennedy.inampudi@driv.com
            attach:
              - /home/inampk48/mksysb_error_report.out
            subtype: html
            charset: utf8
          run_once: True
          delegate_to: pcdcawxlxap01
          when: inventory_hostname in groups['captaix']
        - name: Generate Service Now incident
          mail:
            subject: mksysb failed - Please check and rerun mksysb on {{ inventory_hostname }}
            body: |
              %TYPE=Incident
              group_name: GIOS Maint. - Unix
              category: Unix Server
              subcategory: Process Availability
              cmdb_ci: {{ inventory_hostname }}

              ###{{ inventory_hostname }}###
              --------------------------
              {{ mksys.stdout }}
              {{ mksys.stderr }}
            from: "Unix Mksysb Automation <root@pcdcawxlxap01.driv.com>"
            to:
              - servicenow@tenneco.com
          when: "'Completed Successfully' not in mksys.stdout and (inventory_hostname in groups['mppsaix'])"
          delegate_to: pcdcawxlxap01
        - name: Generate Service Now incident
          mail:
            subject: mksysb failed - Please check and rerun mksysb on {{ inventory_hostname }}
            body: |
              %TYPE=Incident
              group_name: ISD_UNIX
              category: Unix Server
              subcategory: Process 
              cmdb_ci: {{ inventory_hostname }}

              ###{{ inventory_hostname }}###
              --------------------------
              {{ mksys.stdout }}
              {{ mksys.stderr }}
            from: "Unix Mksysb Automation <root@pcdcawxlxap01.driv.com>"
            to:
              - servicenow@tenneco.com
          when: "'Completed Successfully' not in mksys.stdout and (inventory_hostname in groups['captaix'])"
          delegate_to: pcdcawxlxap01